### ISSUE TITLE
onError() not called if download corrupt

### ISSUE THREAD

**Issue by mikehardy** [mikehardy/react-native-update-apk#14]
Not sure why, and v3.2.5 was supposed to fix it, but if you attempt to fetch an empty file (for instance) the download will "succeed", but then fetching APK info in the native module fails. That error is successfully logged (so you can see it in dev with `react-native log-android`) but the onError handler should be called as well so that you can react to it in code. Right now it just appears to be a "successful" download but nothing happens in the end.

**Comment by mikehardy** [comment]
If there is insufficient space, this happens also

**Comment by mikehardy** [comment]
Implementation thoughts - 

- Add a dependency on react-native-device-info if there is not one already
- Use react-native-device-info to check for free space in the download directory (maybe different file system, so be careful - cache, or external, etc)
- If there is not sufficient free space abort the fetch and call onError with a good error message 'errorInsufficientFreeSpace' or similar so the caller can give user appropriate message
- If there is space, do the fetch but do a basic validity check on the file (compare a checksum if it is in the descriptor - #6, for instance) and call onError if the file is invalid (maybe 'errorInvalidDownload')

Development of library code is difficult for react-native, in my experience. If the development cycle is to try it in react-native itself you have to use the example project and copy your changes into example/node_modules/rn-update-apk/etc/etc then re-run, which is slow.

I recommend using jest automated testing, creating a `__test__` directory in react-native-update-apk, creating a test that fails (by mocking out the native filesystem space check and download part to return similar errors) and getting the code working that way.

Final verification can be done by extending the example app to have a separate update button to fetch a sample descriptor for an update with an absurd size (100TB or similar) and a sample update button to fetch a very small APK but with mis-matched checksum to show library users how error handling should work

**Comment by mikehardy** [comment]
Related - got a crash report from a user that cancelled the process while it was running - so clearly interruptions are not handled well: 

```
Fatal Exception: java.lang.SecurityException: Uid 10119 does not have permission to uri 0 @ content://com.kullki.kscore.provider/cache/NewApp.apk
       at android.os.Parcel.readException(Parcel.java:1692)
       at android.os.Parcel.readException(Parcel.java:1645)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerProxy.java:3101)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
       at android.app.ContextImpl.startActivity(ContextImpl.java:791)
       at android.app.ContextImpl.startActivity(ContextImpl.java:768)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
       at net.mikehardy.rnupdateapk.RNUpdateAPK.installApk(RNUpdateAPK.java)
       at java.lang.reflect.Method.invoke(Method.java)
```

All of the error-handling will be worked on in a batch shortly, it's getting closer to the top of the todo list

**Comment by mikehardy** [comment]
I'm not attempting to solve all the problems at once here (out of space etc), but I think I'm correctly re-throwing the exception now, which should result in all the error handlers being called correctly if there is a problem
